<link rel="stylesheet" href="{{asset('assets/user/css/style.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/css/cart.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/css/media.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/css/animate.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/fontawesome/all.css')}}">
<link rel="stylesheet" href="{{asset('assets/bootstrap/bootstrap.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/slick/slick.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/slick/slick-theme.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/slick/slick-style.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/owlcarousel2/owl.carousel.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/owlcarousel2/owl.theme.default.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/sweetalert/sweetalert2.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/css/register.css')}}">
<link rel="stylesheet" href="{{asset('assets/user/select2/select2.css')}}">